#!/bin/bash
# Integration test runner for prod code verification
#
# This script runs the integration test with appropriate settings.
# Update this script as needed when adding new test phases.
#
# Usage:
#   ./test_scripts/run_test.sh
#   # Or with custom settings:
#   MODEL_NAME="meta-llama/Llama-3.1-8B-Instruct" NUM_SAMPLES=5 ./test_scripts/run_test.sh

set -e  # Exit on error

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Default settings
MODEL_NAME="${MODEL_NAME:-meta-llama/Llama-3.1-8B-Instruct}"
NUM_SAMPLES="${NUM_SAMPLES:-5}"
CHUNK_SIZE="${PREFILL_CHUNK_SIZE:-1024}"
# Output dir will be auto-generated with descriptive name if not set or empty
# Only set OUTPUT_DIR if it's actually provided and non-empty
if [ -z "${OUTPUT_DIR}" ]; then
    unset OUTPUT_DIR  # Let Python script auto-generate
fi

# Sparse attention parameters
ORACLE_TOPK_HEAVY_SIZE="${ORACLE_TOPK_HEAVY_SIZE:-0.1}"
SINK_SIZE="${SINK_SIZE:-128}"
LOCAL_WINDOW_SIZE="${LOCAL_WINDOW_SIZE:-128}"

# Debug flags (set to 1 to enable)
SPARSE_DEBUG="${SPARSE_DEBUG:-1}"

echo "=========================================="
echo "Integration Test Runner"
echo "=========================================="
echo "Model: $MODEL_NAME"
echo "Samples: $NUM_SAMPLES"
echo "Chunk size: $CHUNK_SIZE"
echo "Sparse: Sink=$SINK_SIZE, Local=$LOCAL_WINDOW_SIZE, OracleTopK=$ORACLE_TOPK_HEAVY_SIZE"
echo "Output dir: ${OUTPUT_DIR:-'(auto-generated by Python script)'}"
echo "=========================================="

# Only create output directory if explicitly provided
if [ -n "${OUTPUT_DIR}" ]; then
    mkdir -p "$OUTPUT_DIR"
fi

# Set environment variables
export MODEL_NAME="$MODEL_NAME"
export NUM_SAMPLES="$NUM_SAMPLES"
export PREFILL_CHUNK_SIZE="$CHUNK_SIZE"
# Only export OUTPUT_DIR if it's set (non-empty)
if [ -n "${OUTPUT_DIR:-}" ]; then
    export OUTPUT_DIR="$OUTPUT_DIR"
fi
export SPARSE_DEBUG="$SPARSE_DEBUG"
export ORACLE_TOPK_HEAVY_SIZE="$ORACLE_TOPK_HEAVY_SIZE"
export SINK_SIZE="$SINK_SIZE"
export LOCAL_WINDOW_SIZE="$LOCAL_WINDOW_SIZE"
# SPARSE_LOG_PATH will be set by Python script after output dir is created

# Change to repo root
cd "$REPO_ROOT"

# Run the test
echo ""
echo "Running integration test..."
echo ""

# Run the test
# Python script will create output directory and print OUTPUT_DIR_ACTUAL
# We'll capture the output and extract the directory path, then move the log file there
python test_scripts/test_integration.py 2>&1 | tee test_log_temp.txt

# Extract output directory from Python script output (look for "OUTPUT_DIR_ACTUAL:" line)
OUTPUT_DIR_ACTUAL=$(grep -m 1 "^OUTPUT_DIR_ACTUAL:" test_log_temp.txt | sed 's/^OUTPUT_DIR_ACTUAL: //' | tr -d '[:space:]')

# Move log file to output directory if we found it
if [ -n "$OUTPUT_DIR_ACTUAL" ] && [ -d "$OUTPUT_DIR_ACTUAL" ]; then
    mv test_log_temp.txt "${OUTPUT_DIR_ACTUAL}/test_log.txt"
    echo ""
    echo "✓ Log file saved to: ${OUTPUT_DIR_ACTUAL}/test_log.txt"
else
    # Fallback: keep it as test_log.txt in current directory
    mv test_log_temp.txt test_log.txt
    echo ""
    echo "⚠️  Warning: Could not determine output directory, log saved as test_log.txt"
fi

echo ""
echo "=========================================="
echo "Test completed!"
if [ -n "$OUTPUT_DIR_ACTUAL" ] && [ -d "$OUTPUT_DIR_ACTUAL" ]; then
    echo "Results saved to: $OUTPUT_DIR_ACTUAL"
elif [ -n "${OUTPUT_DIR:-}" ]; then
    echo "Results saved to: $OUTPUT_DIR"
else
    echo "Results saved to: (check Python script output for auto-generated directory)"
fi
echo "=========================================="



echo ""
echo "=========================================="
echo "Test completed!"
if [ -n "$OUTPUT_DIR_ACTUAL" ] && [ -d "$OUTPUT_DIR_ACTUAL" ]; then
    echo "Results saved to: $OUTPUT_DIR_ACTUAL"
elif [ -n "${OUTPUT_DIR:-}" ]; then
    echo "Results saved to: $OUTPUT_DIR"
else
    echo "Results saved to: (check Python script output for auto-generated directory)"
fi
echo "=========================================="

